# Generated by Django 3.0.5 on 2021-06-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greek_food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
