# Generated by Django 3.0.5 on 2021-06-21 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greek_food', '0002_auto_20210621_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='greek_food.CafePlaces'),
        ),
    ]
