# Generated by Django 3.0.5 on 2021-06-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greek_food', '0003_table_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeplaces',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cafeplaces',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
