# Generated by Django 3.0.5 on 2021-06-22 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.list


class Migration(migrations.Migration):

    dependencies = [
        ('greek_food', '0004_auto_20210621_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableListView',
            fields=[
                ('table_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='greek_food.Table')),
            ],
            bases=(django.views.generic.list.ListView, 'greek_food.table'),
        ),
    ]
