# Generated by Django 3.0.5 on 2021-06-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greek_food', '0005_tablelistview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableListView',
        ),
    ]
